config/routes.rb
Rails.application.routes.draw do

  get    "/admin/users/:id/edit", to: "admin/users#edit", as: :edit_admin_user
  patch  "/admin/users/:id", to:  "admin/users#update", as: :admin_user
  put    "/admin/users/:id", to:  "admin/users#update"
  get    "/admin/dashboard", to: "admin/users#show", as: :admin_dashboard
  post   "/admin/animals", to: "admin/animals#create", as: :admin_animals
  get    "/admin/animals/new", to: "admin/animals#new", as: :new_admin_animal
  get    "/admin/animals/:id/edit", to: "admin/animals#edit", as: :edit_admin_animal
  patch  "/admin/animals/:id", to: "admin/animals#update", as: :admin_animal
  put    "/admin/animals/:id", to: "admin/animals#update"

  get    "/users/new", to: "users#new", as: :new_user
  post   "users", to: "users#create", as: :users

  get    "/animals", to: "animals#index", as: :animals
  get    "/login", to: "sessions#new", as: :login
  post   "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get    "/dashboard", to: "users#show", as: :dashboard
  root to: "animals#index"

  patch "/durations/:id", to: "durations#update", as: :duration
  put   "/durations/:id", to: "durations#update"

  post   "/favorite_animals", to: "favorite_animals#create", as: :favorite_animals
  delete "/favorite_animals/:id", to: "favorite_animals#destroy", as: :favorite_animal
  get    "/favorites", to: "favorite_animals#index"

  post   "/visit_animals", to: "visit_animals#create", as: :visit_animals
  delete "/visit_animals/:id", to: "visit_animals#destroy", as: :visit_animal

  get  "/visits", to: "visits#index", as: :visits
  post "/visits", to: "visits#create"
  get  "/visits/new", to: "visits#new", as: :new_visit
  get  "visits/:id", to: "visits#show", as: :visit
  patch "/visits/plus", to: "visit_animals#plus", as: :visits_plus
  patch "/visits/minus", to: "visit_animals#minus", as: :visits_minus

  get "/animals/:id", to: "animals#show", as: :animal
  get "/:type", to: "species#show"
end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :user
  has_many :animal_visits
  has_many :animals, through: :animal_visits
  validates :user_id, presence: true
  validates :date, presence: true

  validate :date_cannot_be_in_the_past

  enum status: ["Scheduled", "Cancelled", "Confirmed", "Completed"]

  def date_cannot_be_in_the_past
    if date.present? && date <= Date.today
      errors.add(:date, "can't be in the past")
    end
  end

  def duration
    animal_visits.sum(:duration)
  end

  def cancelled?
    status == "Cancelled"
  end

  def completed?
    status == "Completed"
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def new
    @visit = Visit.new
    @animals = @visitation.animals
  end

  def create
    @visit = VisitHandler.create_visit(
      current_user,
      visit_params,
      @visitation.contents
    )
    is_valid, message = VisitHandler.verify(@visit, @visitation)
    if is_valid
      UserMailer.scheduled_visit_email(@visit.user).deliver_now
      Text.scheduled_visit_text(current_user, @visit)
      flash[:notice] = message
      redirect_to visits_path
    else
      flash[:error] = message
      redirect_to new_visit_path
    end
  end

  def index
    if current_user
      @visits = current_user.visits
      @message = get_visits_message(@visits)
    else
      render file: "public/404"
    end
  end

  def show
    begin
      @visit = current_user.visits.find(params[:id])
    rescue
      render file: "/public/404"
    end
  end

private
  def visit_params
    params.require(:visit).permit(:date, :time)
  end

  def get_visits_message(visits)
    if visits.count == 0
      "You have not scheduled any visits"
    else
      "Your scheduled visits:"
    end
  end
end

app/views/visits/index.html.erb
<div class="container">
  <h3 class="center pad-top-50"><%= @message %></h3>
  <% @visits.each do |visit| %>
    <div>
      <div class="pad-bottom-20">
      <div class="divider"></div>
      <h4><%= link_to "#{visit.date}", visit_path(visit) %></h4>

      <ul>
        <li><%= "Visitation Status: #{visit.status}" %></li>
        <li><%= "Schedule for #{visit.date.strftime("%A, %b %d, %Y")}." %></li>
      </ul>

        <% visit.animals.each do |animal| %>
          <%= link_to "#{Animal.find(animal.id).name}", animal_path(animal.id) %><br>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/visits/new.html.erb
<div class="container">
  <h2 class="center pad-top-50"> Set an Appointment </h2>
  <ul class="collection">
    <% @animals.each_with_index do |animal, index| %>
      <li class="collection-item avatar">
        <a href="<%= animal_path(animal) %>"><img src="<%= animal.image_path %>" alt="<%= animal.name %>" class="circle"></a>
        <div class="center"><b><%= link_to animal.name, animal_path(animal) %></b></div>
        <div class="center section">
          <%= link_to "-", {controller: "visit_animals", action: "minus", animal_id: animal.id}, class: "btn waves-effect waves-light", method: :patch %>
          <h5 class="inline-block pad-left-small pad-right-small"><%= @visitation.contents[animal.id.to_s] %></h5>
          <%= link_to "+", {controller: "visit_animals", action: "plus", animal_id: animal.id}, class: "btn waves-effect waves-light", method: :patch %>
        </div><br/><br/>
      </li>
    <% end %>
  </ul>

  <%= form_for(@visit) do |f| %>
    <div class="center">
      <h5>Visit Duration: <%= @visitation.total_duration %> minutes</h5>
      <br/>
      <div class="date-form"><%= f.datetime_field :date, placeholder: "select a date", class: "datepicker" %></div>
      <br/>
      <%= f.submit class: "btn waves-effect waves-light" %>
    </div>
  <% end %>

</div>

app/views/visits/show.html.erb
<div class="container">

  <h2 class="pad-top-50"><%= "Visit for #{@visit.date}" %></h2>

  <b><%= "Visitation Status: " %></b><%= "#{@visit.status}" %><br>
  <% if @visit.cancelled? or @visit.completed? %>
    <%= "Status changed to #{@visit.status.upcase} at #{@visit.updated_at.localtime.strftime("%B %e at %l:%M %p")}." %><br>
  <% else %>
    <%= "Scheduled for #{@visit.date.strftime("%A, %b %d, %Y")}." %><br>
  <% end %>
  <%= "Reservation made on #{@visit.created_at.localtime.strftime("%B %e at %l:%M %p")}." %><br/><br/>
    <% @visit.animals.each do |animal| %>
      <%= link_to "#{Animal.find(animal.id).name}", animal_path(animal.id) %>
      <div class="pad-left-small"><%= "Meeting duration: #{animal.animal_visits.find_by(visit: @visit.id).duration}" %></div><br>
    <% end %>
  <b><%= "Total duration of this visit: #{@visit.duration} minutes" %></b><br>
</div>