config/routes.rb
Rails.application.routes.draw do

  get    "/admin/users/:id/edit", to: "admin/users#edit", as: :edit_admin_user
  patch  "/admin/users/:id", to:  "admin/users#update", as: :admin_user
  put    "/admin/users/:id", to:  "admin/users#update"
  get    "/admin/dashboard", to: "admin/users#show", as: :admin_dashboard
  post   "/admin/animals", to: "admin/animals#create", as: :admin_animals
  get    "/admin/animals/new", to: "admin/animals#new", as: :new_admin_animal
  get    "/admin/animals/:id/edit", to: "admin/animals#edit", as: :edit_admin_animal
  patch  "/admin/animals/:id", to: "admin/animals#update", as: :admin_animal
  put    "/admin/animals/:id", to: "admin/animals#update"

  get    "/users/new", to: "users#new", as: :new_user
  post   "users", to: "users#create", as: :users

  get    "/animals", to: "animals#index", as: :animals
  get    "/login", to: "sessions#new", as: :login
  post   "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get    "/dashboard", to: "users#show", as: :dashboard
  root to: "animals#index"

  patch "/durations/:id", to: "durations#update", as: :duration
  put   "/durations/:id", to: "durations#update"

  post   "/favorite_animals", to: "favorite_animals#create", as: :favorite_animals
  delete "/favorite_animals/:id", to: "favorite_animals#destroy", as: :favorite_animal
  get    "/favorites", to: "favorite_animals#index"

  post   "/visit_animals", to: "visit_animals#create", as: :visit_animals
  delete "/visit_animals/:id", to: "visit_animals#destroy", as: :visit_animal

  get  "/visits", to: "visits#index", as: :visits
  post "/visits", to: "visits#create"
  get  "/visits/new", to: "visits#new", as: :new_visit
  get  "visits/:id", to: "visits#show", as: :visit
  patch "/visits/plus", to: "visit_animals#plus", as: :visits_plus
  patch "/visits/minus", to: "visit_animals#minus", as: :visits_minus

  get "/animals/:id", to: "animals#show", as: :animal
  get "/:type", to: "species#show"
end

app/views/shared/_all_pets.html.erb
<div class="col s6 m4 l4">
  <div class="card small">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="<%= element.image_path %>">
    </div>
    <div class="card-content activator">
      <ul class="container center">
        <li><b><%= element.name %></b></li>
        <div class="divider"></div>
        <li><%= element.age.capitalize %></li>
        <div class="divider"></div>
        <li><%= element.breed.capitalize %></li>
        <div class="divider"></div>
        <li><%= element.sex.capitalize %></li>
      </ul>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><%= element.name %><i class="material-icons right">close</i></span>
      <p class="truncate"><%= element.description %></p>
      <div class="pad-top-50 center">
        <div id="<%= element.id %>" class="pad-left-small inline">
          <%= button_to favorite_animals_path(animal_id: element.id), method: :post, :class => "btn-floating green tooltipped", :'data-position' => "top", :'data-delay' => "50", :'data-tooltip' => "Add to Favorites" do %>
            <i class="material-icons">favorite</i>
          <% end %>
        </div>
          <div class="pad-left-small inline">
          <%= link_to animal_path(element), :class => "btn-floating blue tooltipped", :'data-position' => "top", :'data-delay' => "50", :'data-tooltip' => "Meet me!" do %>
            <i class="material-icons">pets</i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer footer-small">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">MaxFund</h5>
        <p class="grey-text text-lighten-4">MaxFund is a true no kill animal shelter and adoption center that challenges the traditional methods of animal sheltering by leading the no kill movement in Colorado. We strive to give animals, including the injured, abandoned, and abused, a "second chance at life."</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <ul>
          <li><%= link_to "MaxFund.org", "https://www.maxfund.org/", class: "waves-effect waves-light btn-flat hoverable white-text" %></li><br/>
          <li><%= link_to "Github Repo", "https://github.com/drew-t/little_shop", class: "waves-effect waves-light btn-flat hoverable white-text" %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="mobile-collapse">
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo center">MaxFund</a>
      <a id="navbar" href="#" data-activates="navbar-slider" class="button-collapse right pad-right-small"><i class="material-icons">menu</i></a>
      <a id="sidebar" href="#" data-activates="sidebar-slider" class="button-collapse left pad-left-small"><i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">
        <% if current_user %>
          <%= link_to "Log Out", logout_path, method: :delete %>
        <% else %>
          <%= link_to "Log In/Create Account", login_path %>
        <% end %>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Donate</a></li>
      </ul>
      <ul class="right hide-on-med-and-down">
        <li><a href="/dogs">Adopt a Dog</a></li>
        <li><a href="/cats">Adopt a Cat</a></li>
        <li><a href="/favorites">Favorites (<%= @favorite.total %>)</a></li>
      </ul>
      <ul class="side-nav" id="navbar-slider">
        <li><a href="/favorites">Favorites (<%= @favorite.total %>)</a></li>
        <li><a href="/dogs">Adopt a Dog</a></li>
        <li><a href="/cats">Adopt a Cat</a></li>
        <li><a href="#">Volunteers</a></li>
        <li><a href="#">Location &amp; Hours</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Donate</a></li>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_sidebar.html.erb
<ul class="side-nav fixed">

  <li id="logo" ><%= image_tag "maxfund-logo-text.png" %></li>
  <% if current_user && current_user.admin? %>
    <li><a href="/admin/dashboard">Admin Dashboard</a></li>
  <% elsif current_user %>
    <li><a href="/dashboard">User Dashboard</a></li>
  <% end %>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Donate</a></li>
  <li><a href="#">Volunteers</a></li>
  <li><a href="#">Location &amp; Hours</a></li>
</ul>
<ul id="sidebar-slider" class="side-nav">
  <% if current_admin? %>
    <li><a href="/admin/dashboard">Admin Dashboard</a></li>
  <% elsif current_user %>
    <li><a href="/dashboard">User Dashboard</a></li>
  <% end %>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Donate</a></li>
  <li><a href="#">Volunteers</a></li>
  <li><a href="#">Location &amp; Hours</a></li>
</ul>

app/views/shared/_user_form.html.erb
<div class="container pad-top-50">
  <h2 class="center">Register New User</h2>
  <%= form_for @user do |f| %>
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
    <%= f.text_field :email, placeholder: "Email Address" %>
    <%= f.text_field :phone_number, placeholder: "Phone Number" %>
    <%= f.password_field :password, placeholder: "Password" %>
    <%= f.submit "Create Account", class: "btn waves-effect waves-light" %>
  <% end %>
</div>