config/routes.rb
Rails.application.routes.draw do

  get    "/admin/users/:id/edit", to: "admin/users#edit", as: :edit_admin_user
  patch  "/admin/users/:id", to:  "admin/users#update", as: :admin_user
  put    "/admin/users/:id", to:  "admin/users#update"
  get    "/admin/dashboard", to: "admin/users#show", as: :admin_dashboard
  post   "/admin/animals", to: "admin/animals#create", as: :admin_animals
  get    "/admin/animals/new", to: "admin/animals#new", as: :new_admin_animal
  get    "/admin/animals/:id/edit", to: "admin/animals#edit", as: :edit_admin_animal
  patch  "/admin/animals/:id", to: "admin/animals#update", as: :admin_animal
  put    "/admin/animals/:id", to: "admin/animals#update"

  get    "/users/new", to: "users#new", as: :new_user
  post   "users", to: "users#create", as: :users

  get    "/animals", to: "animals#index", as: :animals
  get    "/login", to: "sessions#new", as: :login
  post   "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get    "/dashboard", to: "users#show", as: :dashboard
  root to: "animals#index"

  patch "/durations/:id", to: "durations#update", as: :duration
  put   "/durations/:id", to: "durations#update"

  post   "/favorite_animals", to: "favorite_animals#create", as: :favorite_animals
  delete "/favorite_animals/:id", to: "favorite_animals#destroy", as: :favorite_animal
  get    "/favorites", to: "favorite_animals#index"

  post   "/visit_animals", to: "visit_animals#create", as: :visit_animals
  delete "/visit_animals/:id", to: "visit_animals#destroy", as: :visit_animal

  get  "/visits", to: "visits#index", as: :visits
  post "/visits", to: "visits#create"
  get  "/visits/new", to: "visits#new", as: :new_visit
  get  "visits/:id", to: "visits#show", as: :visit
  patch "/visits/plus", to: "visit_animals#plus", as: :visits_plus
  patch "/visits/minus", to: "visit_animals#minus", as: :visits_minus

  get "/animals/:id", to: "animals#show", as: :animal
  get "/:type", to: "species#show"
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :species
  has_many :animal_visits
  before_validation :capitalize_name

  validates_presence_of :name,
                        :breed,
                        :sex,
                        :size,
                        :age,
                        :activity_level,
                        :description,
                        :species_id,
                        :image_path

  enum sex: ["Male", "Female"]
  enum size: ["Toy", "Small", "Medium", "Large", "Extra Large"]
  enum age: ["Baby", "Young", "Adult", "Senior"]
  enum activity_level: ["Couch Potato", "Jogger", "Sprinter"]

  # Overwriting default accessors
  # http://api.rubyonrails.org/classes/ActiveRecord/Base.html
  # overriding setter methods for default columns accessors because
  # f.collection_select returns enum values as strings when integer
  # required

  def sex=(val)
    val ? super(val.to_i) : super(val)
  end

  def size=(val)
    val ? super(val.to_i) : super(val)
  end

  def age=(val)
    val ? super(val.to_i) : super(val)
  end

  def activity_level=(val)
    val ? super(val.to_i) : super(val)
  end

  def capitalize_name
    name.capitalize! if name
  end

  def self.available
    where(available: true)
  end

  def house_trained_presenter
    house_trained ? "Yes" : "No"
  end

  def spayed_neutered_presenter
    spayed_neutered ? "Yes" : "No"
  end

  def special_needs_presenter
    special_needs ? "Yes" : "No"
  end

  def available_presenter
    available ? "Yes" : "No"
  end
end

app/controllers/admin/animals_controller.rb
class Admin::AnimalsController < Admin::BaseController
  before_action :current_admin?

  def new
    @animal = Animal.new
    render :new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      flash[:success] = "#{@animal.name} has been successfully registered"
      redirect_to animal_path(@animal)
    else
      flash.now[:error] = "One or more valid fields are missing!"
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    @animal.update(animal_params)
    if @animal.save
      flash[:success] = "Animal Successfully Updated"
      redirect_to animal_path(@animal)
    else
      flash.now[:error] = "One or more valid fields are missing!"
      render :edit
    end
  end

  private

  def animal_params
    params.require(:animal).permit(
      :species_id,
      :name,
      :breed,
      :sex,
      :size,
      :age,
      :activity_level,
      :house_trained,
      :spayed_neutered,
      :special_needs,
      :available,
      :description,
      :image_path
    )
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.available
  end


  def show
    @animal = Animal.find(params[:id])
  end
end

app/views/animals/index.html.erb
<h2 class="center pad-top-50">All Pets</h2>
<div class="divider container"></div>
<div class="row section">
  <div class="pad-left-20 pad-right-20">
    <% @animals.each do |animals| %>
        <%= render partial: "shared/all_pets", locals: { element: animals } %>
    <% end %>
  </div>
</div>

app/views/animals/show.html.erb
<div id="show-favorite" class="pad-top-50 pad-left-small">
  <% if @animal.available %>
    <%= link_to "Favorite", favorite_animals_path(animal_id: @animal.id), method: :post, class: "btn waves-effect waves-light" %>
  <% else %>
    <a class="btn disabled tooltipped" data-position="right" data-delay="50" data-tooltip="I've been adopted!">Adopted!</a>
  <% end %>
  <% if current_admin? %>
    <br/><br/><%= link_to "Edit", edit_admin_animal_path(@animal), class: "btn waves-effect waves-light" %>
  <% end %>
</div>
<div class="container pad-top-50 pad-bottom-50 center">
  <div class="section">
    <div class="center">
      <img class="materialboxed" src="<%= @animal.image_path %>" alt="<%= @animal.name %>" data-caption="<%= @animal.name %>" />
    </div>
    <h4><%= @animal.name %></h4>
    <p><%= @animal.description %></p>
    <div class="section">
      <h5>Info</h5>
      <div class="container">
        <div class="container">
          <div class="divider"></div>
          <table class="highlight">
            <tbody>
              <tr>
                <td>Name</td>
                <td class="secondary-content"><%= @animal.name %></td>
              </tr>
              <tr>
                <td>Age:</td>
                <td class="secondary-content"><%= @animal.age %></td>

              </tr>
              <tr>
                <td>Breed</td>
                <td class="secondary-content"><%= @animal.breed.capitalize %></td>
              </tr>
              <tr>
                <td>Sex</td>
                <td class="secondary-content"><%= @animal.sex %></td>
              </tr>
              <tr>
                <td>Size</td>
                <td class="secondary-content"><%= @animal.size %></td>
              </tr>
              <tr>
                <td>Activity Level</td>
                <td class="secondary-content"><%= @animal.activity_level %></td>

              </tr>
              <tr>
                <td>House Trained</td>
                <td class="secondary-content"><%= @animal.house_trained_presenter %></td>
              </tr>
              <tr>
                <td>Spayed/Neutered</td>
                <td class="secondary-content"><%= @animal.spayed_neutered_presenter %></td>
              </tr>
              <tr>
                <td>Special Needs</td>
                <td class="secondary-content"><%= @animal.special_needs_presenter %></td>
              </tr>
              <tr>
                <td>Available</td>
                <td class="secondary-content"><%= @animal.available_presenter %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/species_index.html.erb
<div class="container center">
  <h1><%= @species.capitalize %></h1>
<div class="row">
    <% @animals.each do |animal| %>
      <%= render partial: "public/all_pets", locals: { element: animal } %>
    <% end %>
  </div>
</div>