config/routes.rb
Rails.application.routes.draw do

  get    "/admin/users/:id/edit", to: "admin/users#edit", as: :edit_admin_user
  patch  "/admin/users/:id", to:  "admin/users#update", as: :admin_user
  put    "/admin/users/:id", to:  "admin/users#update"
  get    "/admin/dashboard", to: "admin/users#show", as: :admin_dashboard
  post   "/admin/animals", to: "admin/animals#create", as: :admin_animals
  get    "/admin/animals/new", to: "admin/animals#new", as: :new_admin_animal
  get    "/admin/animals/:id/edit", to: "admin/animals#edit", as: :edit_admin_animal
  patch  "/admin/animals/:id", to: "admin/animals#update", as: :admin_animal
  put    "/admin/animals/:id", to: "admin/animals#update"

  get    "/users/new", to: "users#new", as: :new_user
  post   "users", to: "users#create", as: :users

  get    "/animals", to: "animals#index", as: :animals
  get    "/login", to: "sessions#new", as: :login
  post   "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get    "/dashboard", to: "users#show", as: :dashboard
  root to: "animals#index"

  patch "/durations/:id", to: "durations#update", as: :duration
  put   "/durations/:id", to: "durations#update"

  post   "/favorite_animals", to: "favorite_animals#create", as: :favorite_animals
  delete "/favorite_animals/:id", to: "favorite_animals#destroy", as: :favorite_animal
  get    "/favorites", to: "favorite_animals#index"

  post   "/visit_animals", to: "visit_animals#create", as: :visit_animals
  delete "/visit_animals/:id", to: "visit_animals#destroy", as: :visit_animal

  get  "/visits", to: "visits#index", as: :visits
  post "/visits", to: "visits#create"
  get  "/visits/new", to: "visits#new", as: :new_visit
  get  "visits/:id", to: "visits#show", as: :visit
  patch "/visits/plus", to: "visit_animals#plus", as: :visits_plus
  patch "/visits/minus", to: "visit_animals#minus", as: :visits_minus

  get "/animals/:id", to: "animals#show", as: :animal
  get "/:type", to: "species#show"
end

app/controllers/favorite_animals_controller.rb
class FavoriteAnimalsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    animal = Animal.find(params[:animal_id])
    message = @favorite.add_animal(animal.id)
    session[:favorite] = @favorite.contents
    flash[:notice] = message
    redirect_to :back
  end

  def show

  end

  def index
    @animals = @favorite.animals
  end

  def destroy
    animal = Animal.find(params[:id])
    @favorite.remove_item(animal.id, @visitation)
    flash[:notice] = "<a href='/animals/#{animal.id}'>Removed #{animal.name} from favorites.</a>"
    redirect_to :back
  end
end

app/views/favorite_animals/index.html.erb
<div class="container">
  <h2 class="center pad-top-50">Favorites</h2>
  <table>
    <ul class="collection">
      <% @animals.each do |animal| %>
        <li class="collection-item avatar">
          <a href="<%= animal_path(animal) %>"><img id="" src="<%= animal.image_path %>" alt="<%= animal.name %>" class="circle"></a>
          <div id="favorite-info" class="center">
            <span class="title"><b><%= link_to animal.name, animal_path(animal) %></b></span>
            <p>Breed: <%= animal.breed %> <br>
               Age: <%= animal.age %>
            </p><br />
          </div>
          <div class="center">
          <%= link_to "Remove Favorite", favorite_animal_path(animal), method: :delete, class: "waves-effect waves-light btn red", id: "fav#{animal.id}" %>
          <a href="<%= animal_path(animal) %>" class="secondary-content"><i class="material-icons">pets</i></a>
          <% if current_user && @visitation.contents.keys.include?(animal.id.to_s)  %>
            <%= link_to "Remove Visit", visit_animal_path(animal), method: :delete, class: "waves-effect waves-light btn red", id: "visit#{animal.id}" %>
          <% elsif current_user %>
            <%= link_to "Add to Visit", visit_animals_path(animal_id: animal.id), method: :post, class: "btn waves-effect waves-light", id: "visit#{animal.id}" %>
          <% end %><br><br>
          </div>
        </li>
      <% end %>
    </ul>
  </table>
 <% if current_user && @visitation.contents.any? %>
   <div class="center pad-top-20">
     <%= link_to "Schedule Visit", new_visit_path, :class => "btn waves-effect waves-light" %>
   </div>
  <% elsif current_user %>
    <div class="center pad-top-20">
      <a class="btn disabled tooltipped", data-position="top", data-delay='50', data-tooltip="Add an animal to your visit">Schedule Visit</a>
    </div>
  <% else %>
    <h5 class="center"><%= link_to "Log In", login_path %> or <%= link_to "Create Account", new_user_path %> to schedule visit.</h5>
  <% end %>
</div>